Imports DevExpress.DataAccess.UI.Sql

Public Class HoursReport
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        'SqlDataSource1.FillAsync()
        'GridView1.PopulateColumns()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill the SqlDataSource asynchronously
        SqlDataSource1.FillAsync()
    End Sub

    Private Sub BarButtonItem1_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonItem1.ItemClick
        'Dim Path As String = "D:\Work\TELUS\" & "TestExport.xlsx"
        Dim Path As String = "TestExport.xlsx"

        GridControl1.ExportToXlsx(Path)

        Process.Start(Path)
    End Sub

    Private Sub btConfigureConnection_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles btConfigureConnection.ItemClick
        SqlDataSourceUIHelper.ConfigureConnection(SqlDataSource1)
        GridView1.PopulateColumns()
    End Sub

    Private Sub btEditQuery_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles btEditQuery.ItemClick
        SqlDataSourceUIHelper.EditQuery(SqlDataSource1.Queries("HoursSummary"))

        SqlDataSource1.Fill()

        GridView1.PopulateColumns()
    End Sub
End Class