Imports DevExpress.XtraEditors
Imports DevExpress.XtraEditors.Controls
Imports DevExpress.XtraGrid.Columns
Imports DevExpress.XtraGrid.Views.Base
Imports DevExpress.XtraGrid.Views.Grid
Imports DevExpress.XtraLayout
Imports Newtonsoft.Json.Linq
Imports System.ComponentModel
Imports System.Data.OleDb
Imports System.Globalization
Imports System.IO
Imports System.Linq
Imports System.Net
Imports System.Text
Imports System.Text.RegularExpressions
Imports System.Threading
Imports Telerik.Windows.Documents.Spreadsheet.Expressions.Functions

Partial Public Class MenuV2
    Private CurrentUserID As Integer

    Public Sub New()
        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        'Me.repoDateEdit.TodayDate = Now

        Select Case UCase(Environment.UserName)
            Case "T989040", "T970773", "T931026" ', "HELLF"
                navBarControl.ActiveGroup = DefectsNavBarGroup
            Case Else
                navBarControl.ActiveGroup = RequestsNavBarGroup
        End Select
        'Dim RichTxtEdit As RichTextBox
        AddHandler GVIssues.EditFormPrepared, Sub(s, e)
                                                  ' The 'e.BindableControls' collection contains the editors in the Edit Form.
                                                  Dim RichTxtEdit As Control = e.BindableControls(GridColumn34)
                                                  Dim row As DataRow = GVIssues.GetDataRow(e.RowHandle)
                                                  'MsgBox(row("Description").ToString())
                                                  'RichTxtEdit.
                                                  'RichTxtEdit.
                                                  RichTxtEdit.Text = If(String.IsNullOrEmpty(row("Description").ToString()), String.Empty, String.Format(StripTags(row("Description").ToString()))) 'StripTags(row("Description").ToString())
                                                  NewCommentIssueID = CInt(row("ID").ToString)
                                              End Sub

    End Sub
    Private Sub MenuV2_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        LoadDataAsync()
    End Sub

    Private Sub GridView1_CalcPreviewText(sender As Object, e As CalcPreviewTextEventArgs) Handles GVIssues.CalcPreviewText
        e.PreviewText = CalculateMyPreviewText(e.RowHandle)
    End Sub

    Private Function CalculateMyPreviewText(rowHandle As Integer) As String
        On Error Resume Next
        Dim row As DataRow = GVIssues.GetDataRow(rowHandle)
        Dim description As String = row("Description").ToString()
        Return If(String.IsNullOrEmpty(description), String.Empty, String.Format(StripTags(description)))

    End Function

    Function StripTags(ByVal html As String) As String
        On Error Resume Next
        'Return Regex.Replace(html, "<(.|\n)*?>", String.Empty)
        Return Regex.Replace(Regex.Replace(Regex.Replace(Replace(html, "&nbsp;", String.Empty), "<(.|\n)*?>", String.Empty), "(\r?\n){2,}", vbCrLf), "^[\s]+|[\s]+$", String.Empty, RegexOptions.Multiline)
    End Function

    Private Sub RepositoryItemRichTextEdit1_EditValueChanged(sender As Object, e As EventArgs) Handles RepositoryItemRichTextEdit1.EditValueChanged
        'RepositoryItemRichTextEdit1.
    End Sub

    Private Sub BarButtonItem1_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonItem1.ItemClick
        'Dim oFrm As New RadForm1
        'oFrm.Show()
        Application.Restart()
    End Sub

    Private Sub BarToggleSwitchPreview_CheckedChanged(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarToggleSwitchPreview.CheckedChanged
        If Me.BarToggleSwitchPreview.Checked = False Then
            If navigationFrame.SelectedPage Is Me.DefectsNavigationPage Then
                Me.GridView9.OptionsView.ShowPreview = False
            ElseIf navigationFrame.SelectedPage Is Me.RequestsNavigationPage Then
                Me.GVIssues.OptionsView.ShowPreview = False
            End If
        Else
            If navigationFrame.SelectedPage Is Me.DefectsNavigationPage Then
                Me.GridView9.OptionsView.ShowPreview = True
            ElseIf navigationFrame.SelectedPage Is Me.RequestsNavigationPage Then
                Me.GVIssues.OptionsView.ShowPreview = True
            End If
        End If
    End Sub

    Private QryUpdHoursComments As String = String.Empty
    Private issueID As Integer
    Private dateAdded As DateTime
    Private dateAddedRng As DateRangeCollection
    Private quantity As Decimal
    Private employee As String
    Private billable As Boolean
    Private details As String


    Private Sub GVIssues_MouseDown(sender As Object, e As MouseEventArgs) Handles GVIssues.MouseDown
        If (Control.ModifierKeys And Keys.Control) <> Keys.Control Then
            Dim view As GridView = TryCast(sender, GridView)
            Dim hi As DevExpress.XtraGrid.Views.Grid.ViewInfo.GridHitInfo = view.CalcHitInfo(e.Location)
            If hi.InRowCell Then
                If hi.Column.RealColumnEdit.Name = "RepoBtnAddComment" Then
                    Dim row As DataRow = GVIssues.GetDataRow(hi.RowHandle)
                    NewCommentIssueID = CInt(row("ID").ToString)
                    Dim myControl As New AddCommentUserControl()
                    If XtraDialog.Show(myControl, "Enter comment", MessageBoxButtons.OKCancel) = System.Windows.Forms.DialogResult.OK Then
                        QryUpdHoursComments = "INSERT INTO Audit (IssueID, DateAdded, Username, Comment) VALUES (" & NewCommentIssueID & ", #" & Now() & "#, '" & UCase(Environment.UserName) & "', '" & Replace(myControl.Comment, "'", "''") & "')"
                        LoadDataAsync_NavBar("FillAudit")
                    End If
                ElseIf hi.Column.RealColumnEdit.Name = "RepoButtonHours" Then
                    Dim row As DataRow = GVIssues.GetDataRow(hi.RowHandle)
                    NewCommentIssueID = CInt(row("ID").ToString)
                    'Dim myControl As New AddHoursUserControl()
                    Dim myControl As New AddHoursMultiDaysUserControl()
                    If XtraDialog.Show(myControl, "Enter time", MessageBoxButtons.OKCancel) = System.Windows.Forms.DialogResult.OK Then
                        Dim employee As String = Me.Tag
                        Using connection As New OleDb.OleDbConnection(My.Settings.DB_Connection)
                            connection.Open()
                            If myControl.WorkedHours.Count > 1 Then
                                For Each hoursWorked In myControl.WorkedHours
                                    InsertRecords(hoursWorked, NewCommentIssueID, employee, connection)
                                Next
                            Else
                                InsertRecord(myControl.AddDate, NewCommentIssueID, myControl.Quantity, Me.Tag, myControl.Billable, myControl.Details, connection)
                            End If
                        End Using
                        LoadDataAsync_NavBar("FillHours")
                    End If
                End If
            End If
        End If
    End Sub

    Private Sub StatusCbo_EditValueChanged(sender As Object, e As EventArgs) Handles StatusCbo.EditValueChanged

        Dim ticketkey As String
        Dim summary As String
        Dim createdFLEXS As DateTime
        Dim DefOrEnh As String = String.Empty

        If NewValuectrl = "Completed - Defect Created" Or NewValuectrl = "Completed - Enhancement Requested" Then
            If IsNothing(GVIssues.GetFocusedRowCellValue("FLEXS Ticket")) Or IsDBNull(GVIssues.GetFocusedRowCellValue("FLEXS Ticket")) Then
                'XtraMessageBox.Show("The FLEXS ticket field cannot be blank when using this status!", "No FLEXS number!", MessageBoxButtons.OK, MessageBoxIcon.Error)
                Exit Sub
            End If

            If NewValuectrl = "Completed - Defect Created" Then
                DefOrEnh = "Confirmed Defect"
            ElseIf NewValuectrl = "Completed - Enhancement Requested" Then
                DefOrEnh = "Enhancement - Escalated to Product"
            End If
            NewValuectrl = String.Empty
            ticketkey = GVIssues.GetFocusedRowCellValue("FLEXS Ticket") '(colFLEXSTicket).Text 'e.BindableControls(colAudit)
            ' Fetch the ticket details, including comments and activity history
            Dim detailsRequest As HttpWebRequest = DirectCast(WebRequest.Create("https://jira.tools.telushealth.com/rest/api/2/issue/FLEXS-" & ticketkey), HttpWebRequest)
            detailsRequest.Headers.Add("Authorization", "Bearer ODAwNDc5MDE5OTk4Op6GvljcN/HFEyy5z1uJQyoV8F6m") ' Replace YOUR_API_TOKEN with your JIRA API token
            detailsRequest.ContentType = "application/json"
            detailsRequest.Method = "GET"

            'Dim json As String = client.DownloadString(url)

            Dim detailsResponse As WebResponse = detailsRequest.GetResponse()
            Dim detailsReader As StreamReader = New StreamReader(detailsResponse.GetResponseStream())
            Dim detailsResponseString As String = detailsReader.ReadToEnd()


            ' Parse the JSON response to get the comments and activity history
            'Dim obj As JObject = JObject.Parse(json)
            'Dim issues As JArray = obj("issues")
            Dim details As JObject = JObject.Parse(detailsResponseString)
            'Dim summary As String = issue("fields")("summary").ToString()
            summary = details.SelectToken("fields.summary").ToString
            createdFLEXS = CDate(details.SelectToken("fields.created").ToString)

            If XtraMessageBox.Show("This will create a new defect or enhancement record containing the information below, pulled from JIRA." & vbNewLine & vbNewLine & "FLEXS-" & ticketkey & ": " & summary & vbNewLine & vbNewLine & "Do you want to continue?", "Create FLEXS-" & ticketkey & " record?", MessageBoxButtons.YesNo, MessageBoxIcon.Question) = DialogResult.Yes Then

                Using connection As New OleDbConnection(My.Settings.DB_Connection)

                    Dim cmdAddIssue As New OleDbCommand("INSERT INTO Issues (Channel, Client, Title, Description, [Assigned To], [Date Received], Status, Priority, [FLEXS Ticket]) VALUES (" & GVIssues.GetFocusedRowCellValue("Channel") & ", " & GVIssues.GetFocusedRowCellValue("Client") & ", '" & summary.Replace("'", "''") & "' , 'FLEXS Ticket', 226, #" & createdFLEXS & "#, '" & DefOrEnh & "', NULL, " & ticketkey.Replace("FLEXS-", String.Empty) & ");", connection)
                    connection.Open()
                    If cmdAddIssue.ExecuteNonQuery > 0 Then
                        MsgBox("Defect Created!", vbOKOnly, "Success")
                    Else
                        MsgBox("Failed to create new defect!", vbOKOnly, "Error")
                    End If
                End Using
            Else
                Me.StatusCbo.CancelUpdate()
                GVIssues.SetFocusedRowCellValue("Status", OldValuectrl) ' = OldValuectrl 'Me.StatusCbo.Tag
            End If
        ElseIf NewValuectrl = "Completed" Then
            If GVIssues.GetFocusedRowCellValue("Category") = "Troubleshooting" Then
                Me.StatusCbo.CancelUpdate()
                GVIssues.SetFocusedRowCellValue("Status", OldValuectrl)
                GVIssues.FocusedColumn = GVIssues.Columns("Category")
                Exit Sub
            End If
        Else
                Exit Sub
        End If

    End Sub


    Private Sub GVIssues_ValidatingEditor(sender As Object, e As DevExpress.XtraEditors.Controls.BaseContainerValidateEditorEventArgs) Handles GVIssues.ValidatingEditor

        'Dim view As ColumnView = sender
        'Dim column As DevExpress.XtraGrid.Columns.GridColumn = If(TryCast(e, EditFormValidateEditorEventArgs)?.Column, view.FocusedColumn)
        'If column.Name <> "colStatus" Then Exit Sub
        'If NewValuectrl = "Completed - Defect Created" Or NewValuectrl = "Completed - Enhancement Requested" Then
        '    If GVIssues.GetFocusedRowCellValue("FLEXS Ticket") Is String.Empty Or IsNothing(GVIssues.GetFocusedRowCellValue("FLEXS Ticket")) Or IsDBNull(GVIssues.GetFocusedRowCellValue("FLEXS Ticket")) Then
        '        ExcValid = "NoFLEXS"
        '        e.Valid = False
        '    End If
        'ElseIf NewValuectrl = "Completed" Then
        '    If GVIssues.GetFocusedRowCellValue("Category") = "Troubleshooting" Then
        '        ExcValid = "CompAndTroubleshoot"
        '        e.Valid = False
        '        e.ErrorText = "A request cannot be marked as Completed while category is Troubleshooting."
        '    End If
        'End If
        'If (Convert.ToInt32(e.Value) < 0) Or (Convert.ToInt32(e.Value) > 1000000) Then
        '    e.Valid = False
        'End If
    End Sub

    Dim ExcValid As String = ""

    Private Sub GVIssues_InvalidValueException(sender As Object, e As DevExpress.XtraEditors.Controls.InvalidValueExceptionEventArgs) Handles GVIssues.InvalidValueException
        Dim view As ColumnView = sender
        If view Is Nothing Then
            Return
        End If
        'e.ExceptionMode = ExceptionMode.DisplayError

        e.ExceptionMode = ExceptionMode.DisplayError 'Ignore
        Select Case ExcValid
            Case "NoFLEXS"
                e.WindowCaption = "FLEXS required!"
                e.ErrorText = "The FLEXS ticket field cannot be left blank when using this status!"
                ExcValid = ""
            Case "CompAndTroubleshoot"
                e.WindowCaption = "Completed request cannot be categorized as Troubleshooting"
                e.ErrorText = "Update the category with the appropriate value and try again"
                ExcValid = ""
        End Select

    End Sub

    'XtraMessageBox.Show("The FLEXS ticket field cannot be blank when using this status!", "No FLEXS number!", MessageBoxButtons.OK, MessageBoxIcon.Error)
    Private OldValuectrl As String
    Private NewValuectrl As String
    Private Sub StatusCbo_EditValueChanging(sender As Object, e As ChangingEventArgs) Handles StatusCbo.EditValueChanging
        OldValuectrl = e.OldValue.ToString
        NewValuectrl = e.NewValue.ToString
    End Sub


#Region "Data Updates"

    Private Sub GVIssues_RowUpdated(sender As Object, e As RowObjectEventArgs) Handles GVIssues.RowUpdated

        Try
            IssuesTableAdapter1.Update(Me.ProdSupport_DataSet1.Issues)
            If e.RowHandle < 0 Then
                Me.IssuesTableAdapter1.ClearBeforeFill = True
                IssuesTableAdapter1.FillLastAdded(ProdSupport_DataSet1.Issues)
                Me.IssuesTableAdapter1.ClearBeforeFill = False
            End If
        Catch Ex As Exception
            Me.StatBarUPDFail.Visibility = DevExpress.XtraBars.BarItemVisibility.Always
            MsgBox("Update failed!" & vbNewLine & vbNewLine & Ex.Message, MsgBoxStyle.Critical, "Error")
            Exit Sub
        End Try
        Me.StatBarUPDSuccess.Visibility = DevExpress.XtraBars.BarItemVisibility.Always
        'MsgBox("Successfully updated the record!", MsgBoxStyle.Information, "Success")




    End Sub

    Private Sub wait(ByVal seconds As Integer)
        For i As Integer = 0 To seconds * 100
            System.Threading.Thread.Sleep(10)
            Application.DoEvents()
        Next
    End Sub

    Private Sub GVIssues_HiddenEditor(sender As Object, e As EventArgs) Handles GVIssues.HiddenEditor

    End Sub

    Private Sub GVIssues_DataSourceChanged(sender As Object, e As EventArgs) Handles GVIssues.DataSourceChanged

    End Sub

    Private NewCommentIssueID As Integer = Nothing

    Private Sub GVIssues_EditFormHidden(sender As Object, e As EditFormHiddenEventArgs) Handles GVIssues.EditFormHidden
        'wait(5)

        'If Me.StatBarUPDSuccess.Visibility = DevExpress.XtraBars.BarItemVisibility.Always Then
        '    Me.StatBarUPDSuccess.Visibility = DevExpress.XtraBars.BarItemVisibility.Never
        'ElseIf Me.StatBarUPDFail.Visibility = DevExpress.XtraBars.BarItemVisibility.Always Then
        '    Me.StatBarUPDFail.Visibility = DevExpress.XtraBars.BarItemVisibility.Never
        'End If
    End Sub

    Private Sub SimpleButton1_Click(sender As Object, e As EventArgs) Handles SimpleButton1.Click
        Dim myControl As New AddHoursUserControl()
        If XtraDialog.Show(myControl, "Enter time", MessageBoxButtons.OKCancel) = System.Windows.Forms.DialogResult.OK Then
            Dim DateHours As DateTime = myControl.AddDate
            Dim Qty As Double = myControl.Quantity
            Dim Billable As Boolean = myControl.Billable
            Dim Details As String = myControl.Details
        End If
    End Sub

#End Region

#Region "Navigation"

    Private Sub navBarControl_ActiveGroupChanged(ByVal sender As Object, ByVal e As DevExpress.XtraNavBar.NavBarGroupEventArgs) Handles navBarControl.ActiveGroupChanged
        Select Case e.Group.Name
            Case "RequestsNavBarGroup"
                navigationFrame.SelectedPageIndex = navBarControl.Groups.IndexOf(e.Group)
                Me.BarToggleSwitchPreview.Checked = Me.GVIssues.OptionsView.ShowPreview = True
            Case "DefectsNavBarGroup"
                navigationFrame.SelectedPageIndex = navBarControl.Groups.IndexOf(e.Group)
                Me.BarToggleSwitchPreview.Checked = Me.GridView9.OptionsView.ShowPreview = True
            Case Else
        End Select
        'navigationFrame.SelectedPageIndex = navBarControl.Groups.IndexOf(e.Group)
    End Sub

    Private Sub navigationFrame_SelectedPageChanging(sender As Object, e As DevExpress.XtraBars.Navigation.SelectedPageChangingEventArgs) Handles navigationFrame.SelectedPageChanging
        'MsgBox(e.OldPage.Caption)
    End Sub

    Private Sub svgFLEXSBack_Click(sender As Object, e As EventArgs) Handles svgFLEXSBack.Click
        Me.navigationFrame.SelectPrevPage()
        Me.NavBarJIRASync.Enabled = True
    End Sub

    Private Sub barButtonNavigation_ItemClick(ByVal sender As Object, ByVal e As DevExpress.XtraBars.ItemClickEventArgs) Handles requestsBarButtonItem.ItemClick, DefectsBarButtonItem.ItemClick
        navBarControl.ActiveGroup = If(e.Item.Caption = "Requests", RequestsNavBarGroup, DefectsNavBarGroup)
    End Sub

    Private Sub NavBarJIRASync_LinkClicked(sender As Object, e As DevExpress.XtraNavBar.NavBarLinkEventArgs) Handles NavBarJIRASync.LinkClicked
        navigationFrame.SelectedPage = Me.JIRASyncNavigationPage 'navigationFrame.Pages(2)
        Me.NavBarJIRASync.Enabled = False
    End Sub

    Private Sub navBarControl_LinkClicked(sender As Object, e As DevExpress.XtraNavBar.NavBarLinkEventArgs) Handles navBarControl.LinkClicked
        If e.Link.Caption = "JIRA Sync" And Me.navigationFrame.SelectedPage IsNot Me.JIRASyncNavigationPage Then
            Me.NavBarJIRASync.Enabled = False
            navigationFrame.SelectedPage = Me.JIRASyncNavigationPage
        ElseIf e.Link.Caption IsNot "JIRA Sync" And Me.navigationFrame.SelectedPage Is Me.JIRASyncNavigationPage Then
            Me.NavBarJIRASync.Enabled = True
            If e.Link.Group.Name = "DefectsNavBarGroup" And Me.navigationFrame.SelectedPage IsNot Me.DefectsNavigationPage Then
                navigationFrame.SelectedPage = Me.DefectsNavigationPage
            ElseIf e.Link.Group.Name = "RequestsNavBarGroup" And Me.navigationFrame.SelectedPage IsNot Me.RequestsNavigationPage Then
                navigationFrame.SelectedPage = Me.RequestsNavigationPage
            End If
        End If
        LoadDataAsync_NavBar(e.Link.Caption)
    End Sub

#End Region

#Region "Data Loading"

    Private Sub LoadDataAsync()

        'Telerik.WinControls.UI.RadOverlayManager.Show(navBarControl)
        Me.GVIssues.ShowLoadingPanel()

        ' Start a new thread to load the data asynchronously
        Dim loadThread As New Thread(Sub()

                                         Dim newDataSet = FillDataSet()
                                         ''FillData("FillPriorities")
                                         ''FillData("FillStatuses")
                                         ''FillData("FillCategories")
                                         'FillData("FillContacts_Extended")
                                         'FillData("FillAnalysts")
                                         'FillData("FillClients")
                                         'FillData("FillChannels")
                                         ''FillData("FillIssues")
                                         'FillData("FillHours")
                                         'FillData("FillAudit")

                                         Me.Invoke(New Action(Sub()
                                                                  ' Enable UI controls
                                                                  ' Merge newDataSet into ProdSupport_DataSet1
                                                                  'MsgBox("Starting to merge!")
                                                                  Me.ProdSupport_DataSet1.Merge(newDataSet)
                                                                  'Me.Enabled = True
                                                                  'Telerik.WinControls.UI.RadOverlayManager.Close()
                                                                  Me.GVIssues.HideLoadingPanel()
                                                                  If IsNothing(Me.Tag) Then
                                                                      'SplashScreenManager1.CloseWaitForm()
                                                                      Dim conn As New OleDbConnection(My.Settings.DB_Connection)
                                                                      Dim cmd As New OleDbCommand("SELECT ID, [Contact Name] FROM [Contacts Extended] WHERE TELUS_ID = @username", conn)
                                                                      cmd.Parameters.AddWithValue("@username", UCase(Environment.UserName))

                                                                      Using conn
                                                                          conn.Open()
                                                                          'Me.Tag = cmd.ExecuteScalar.ToString
                                                                          Dim reader As OleDbDataReader = cmd.ExecuteReader()
                                                                          If reader.Read() Then
                                                                              CurrentUserID = CInt(reader("ID").ToString())
                                                                              Me.Tag = reader("Contact Name").ToString()
                                                                          End If
                                                                      End Using
                                                                      conn.Close()
                                                                  End If
                                                              End Sub))
                                     End Sub)

        ' Start the thread
        loadThread.Start()
    End Sub

    Private Function FillDataSet() As ProdSupport_DataSet_Async
        ' Create a new instance of the dataset
        Dim newDataSet As New ProdSupport_DataSet_Async()

        ' Fill the dataset
        Try
            Me.Contacts_ExtendedTableAdapter_Async.Fill(newDataSet.Contacts_Extended)
            Me.AnalystsTableAdapter_Async.Fill(newDataSet.Analysts)
            Me.ClientsTableAdapter_Async.Fill(newDataSet.Clients)
            Me.ChannelsTableAdapter_Async.Fill(newDataSet.Channels)
            Me.Tbl_HoursWorkedLogTableAdapter_Async.Fill(newDataSet.tbl_HoursWorkedLog)
            Me.AuditTableAdapter_Async.Fill(newDataSet.Audit)
        Catch ex As Exception
            ' Log the exception details
            MessageBox.Show("An error occurred while filling the data: " & ex.Message)
        End Try

        ' Return the filled dataset
        Return newDataSet
    End Function

    Private Function FillDataSetAuditHours(ByVal fillMethod As String) As ProdSupport_DataSet_Async
        ' Create a new instance of the dataset
        Dim newDataSet As New ProdSupport_DataSet_Async()

        If fillMethod = "FillAudit" Then
            Dim conn As New OleDbConnection(My.Settings.DB_Connection)
            Dim cmd As New OleDbCommand(QryUpdHoursComments, conn)

            Using conn
                conn.Open()
                If CInt(cmd.ExecuteNonQuery) > 0 Then
                    'MsgBox("Comment saved!", , "Success!")
                Else
                    'MsgBox("Comment failed to save!", "Error!")
                End If
            End Using
            Me.AuditTableAdapter_Async.Fill(newDataSet.Audit)

        ElseIf fillMethod = "FillHours" Then
            Me.Tbl_HoursWorkedLogTableAdapter_Async.Fill(newDataSet.tbl_HoursWorkedLog)
        ElseIf fillMethod = "AddClient" Then
            Dim conn As New OleDbConnection(My.Settings.DB_Connection)
            Dim cmd As New OleDbCommand(QryUpdHoursComments, conn)

            Using conn
                conn.Open()
                If CInt(cmd.ExecuteNonQuery) > 0 Then
                    MsgBox("Client created!", , "Success!")
                Else
                    MsgBox("Client failed to save!", "Error!")
                End If
            End Using
            Me.ClientsTableAdapter_Async.Fill(newDataSet.Clients)
        ElseIf fillMethod = "AddContact" Then
            Dim conn As New OleDbConnection(My.Settings.DB_Connection)
            Dim cmd As New OleDbCommand(QryUpdHoursComments, conn)

            Using conn
                conn.Open()
                If CInt(cmd.ExecuteNonQuery) > 0 Then
                    MsgBox("Contact created!", , "Success!")
                Else
                    MsgBox("Contact failed to save!", "Error!")
                End If
            End Using
            Me.Contacts_ExtendedTableAdapter_Async.Fill(newDataSet.Contacts_Extended)
            Me.AnalystsTableAdapter_Async.Fill(newDataSet.Analysts)
        Else
            Exit Function
        End If


        ' Fill the dataset
        Try


        Catch ex As Exception
            ' Log the exception details
            MessageBox.Show("An error occurred while filling the data: " & ex.Message)
        End Try

        ' Return the filled dataset
        Return newDataSet
    End Function


    Private Sub FillData(ByVal fillMethod As String)
        ' Call the appropriate Fill method on the appropriate TableAdapter
        Try
            Select Case fillMethod
                'Case "FillPriorities"
                '    Me.PrioritiesTableAdapter.Fill(Me.ProdSupport_DataSet.Priorities)
                'Case "FillStatuses"
                '    Me.StatusesTableAdapter.Fill(Me.ProdSupport_DataSet.Statuses)
                'Case "FillCategories"
                '    Me.CategoriesTableAdapter.Fill(Me.ProdSupport_DataSet.Categories)
                Case "FillContacts_Extended"
                    Me.Contacts_ExtendedTableAdapter.Fill(Me.ProdSupport_DataSet1.Contacts_Extended)
                Case "FillAnalysts"
                    Me.AnalystsTableAdapter.Fill(Me.ProdSupport_DataSet1.Analysts)
                Case "FillClients"
                    Me.ClientsTableAdapter.Fill(Me.ProdSupport_DataSet1.Clients)
                Case "FillChannels"
                    Me.ChannelsTableAdapter.Fill(Me.ProdSupport_DataSet1.Channels)
                Case "FillHours"
                    Me.Tbl_HoursWorkedLogTableAdapter1.ClearBeforeFill = False
                    Me.Tbl_HoursWorkedLogTableAdapter1.Fill(Me.ProdSupport_DataSet1.tbl_HoursWorkedLog)
                Case "FillAudit"
                    Me.AuditTableAdapter1.ClearBeforeFill = False
                    Me.AuditTableAdapter1.Fill(Me.ProdSupport_DataSet1.Audit)
            End Select
        Catch ex As Exception
            ' Log the exception details
            MessageBox.Show("An error occurred while filling the " & fillMethod & " data: " & ex.Message)
        End Try
    End Sub

    Private Sub FillData_NavBar(ByVal fillMethod As String)
        Me.IssuesTableAdapter1.ClearBeforeFill = False
        ' Call the appropriate Fill method on the appropriate TableAdapter
        Me.GVIssues.ShowLoadingPanel()
        Try

            Select Case fillMethod
                Case Me.NavBarResolved.Caption 'Resolved
                    IssuesTableAdapter1.FillByAll(ProdSupport_DataSet1.Issues)
                    issuesBindingSource.Filter = "Status NOT IN ('Escalated - Production Script', 'Escalated to IT', 'Escalated to Product', 'Future Work', 'In Progress', 'Not Started', 'On Hold (Client)', 'Projects', 'Recurring Task','AODA - Confirmed Defect','AODA - Enhancement','Confirmed Defect','Enhancement - Escalated to Product','AODA - Confirmed Defect Fixed','AODA - Enhancement Released','Confirmed Defect - Fixed','Enhancement - Released')"
                Case Me.NavBarAllRequests.Caption 'All Requests
                    Dim Choice As DialogResult
                    Choice = MessageBox.Show("Retrieving all records will take some time!" & vbCrLf & "Are you sure you want to continue?", "Long operation warning", MessageBoxButtons.YesNo, MessageBoxIcon.Warning, MessageBoxDefaultButton.Button2, MessageBoxOptions.DefaultDesktopOnly)
                    If Choice = DialogResult.Yes Then
                        UseWaitCursor = True
                        Me.GVIssues.LoadingPanelVisible = True
                        Me.GVIssues.ShowLoadingPanel()
                        IssuesTableAdapter1.FillByAll(ProdSupport_DataSet1.Issues)
                        issuesBindingSource.RemoveFilter()
                        Me.GVIssues.HideLoadingPanel()
                        Me.GVIssues.LoadingPanelVisible = False
                        UseWaitCursor = False
                    End If
                Case Me.NavBarAssignedMe.Caption 'Assigned To Me
                    IssuesTableAdapter1.FillByAnalyst(ProdSupport_DataSet1.Issues, CurrentUserID)
                    issuesBindingSource.Filter = "Status IN ('Escalated - Production Script', 'Escalated to IT', 'Escalated to Product', 'Future Work', 'In Progress', 'Not Started', 'On Hold (Client)', 'Projects', 'Recurring Task') AND [Assigned To] = " & CurrentUserID
                Case Me.NavBarUnresolved.Caption 'Unresolved
                    IssuesTableAdapter1.FillByActive(ProdSupport_DataSet1.Issues)
                    issuesBindingSource.Filter = "Status IN ('Escalated - Production Script', 'Escalated to IT', 'Escalated to Product', 'Future Work', 'In Progress', 'Not Started', 'On Hold (Client)', 'Projects', 'Recurring Task')"
                Case Me.NavBarDefects.Caption 'Open Defects
                    FLEXSMgmtTableAdapter.FillActiveDefects(ProdSupport_DataSet1.FLEXSMgmt)
                    FLEXSMgmtBindingSource.Filter = "Status IN ('AODA - Confirmed Defect','Confirmed Defect')"
                Case Me.NavBarEnh.Caption 'Open Enhancements
                    FLEXSMgmtTableAdapter.FillActiveEnhancements(ProdSupport_DataSet1.FLEXSMgmt)
                    FLEXSMgmtBindingSource.Filter = "Status IN ('AODA - Enhancement','Enhancement - Escalated to Product')"
                Case Me.NavBarFLEXSDone.Caption 'Closed FLEXS
                    FLEXSMgmtTableAdapter.Fill(ProdSupport_DataSet1.FLEXSMgmt)
                    FLEXSMgmtBindingSource.Filter = "Status IN ('AODA - Confirmed Defect Fixed','AODA - Enhancement Released','Confirmed Defect - Fixed','Enhancement - Released')"
                Case Me.NavBarFLEXS.Caption 'Active FLEXS
                    FLEXSMgmtTableAdapter.FillActiveFLEXS(ProdSupport_DataSet1.FLEXSMgmt)
                    FLEXSMgmtBindingSource.Filter = "Status IN ('AODA - Confirmed Defect','AODA - Enhancement','Confirmed Defect','Enhancement - Escalated to Product')"

            End Select
        Catch ex As Exception
            ' Log the exception details
            MessageBox.Show("An error occurred while filling the " & fillMethod & " data: " & ex.Message)
        End Try
        Me.GVIssues.HideLoadingPanel()
    End Sub

    Sub LoadDataAsync_NavBar(ByVal FillWhat As String)

        ' Start a new thread to load the data asynchronously
        Dim loadThread As New Thread(Sub()
                                         Dim newDataSet = FillDataSetAuditHours(FillWhat)

                                         Me.Invoke(New Action(Sub()
                                                                  If FillWhat = "FillAudit" Then

                                                                      Me.ProdSupport_DataSet1.Merge(newDataSet)

                                                                  ElseIf FillWhat = "FillHours" Then

                                                                      Me.ProdSupport_DataSet1.Merge(newDataSet)
                                                                  ElseIf FillWhat = "AddClient" Then

                                                                      Me.ProdSupport_DataSet1.Merge(newDataSet)
                                                                  ElseIf FillWhat = "AddContact" Then

                                                                      Me.ProdSupport_DataSet1.Merge(newDataSet)
                                                                  Else
                                                                      FillData_NavBar(FillWhat)
                                                                  End If

                                                              End Sub))
                                     End Sub)

        ' Start the thread
        loadThread.Start()
    End Sub
    Private Sub InsertRecords(hoursWorked As HoursWorked, issueID As Integer, employee As String, connection As OleDb.OleDbConnection)

        ' Gets a NumberFormatInfo associated with the en-US culture.
        Dim nfi As NumberFormatInfo = New CultureInfo("en-CA", False).NumberFormat

        ' Displays the same value with a blank as the separator.
        nfi.NumberDecimalSeparator = "."

        Dim sqlQuery As String = "INSERT INTO tbl_HoursWorkedLog (Issue_ID, Hours_Worked_Date, Hours_Worked_Amt, Employee, Billable, Details) VALUES (?, ?, ?, ?, ?, ?)"

        Using command As New OleDb.OleDbCommand(sqlQuery, connection)
            command.Parameters.Add(New OleDb.OleDbParameter("Issue_ID", CInt(issueID))) 'Convert.ToInt32(issueID)))
            command.Parameters.Add(New OleDb.OleDbParameter("Hours_Worked_Date", OleDb.OleDbType.Date))
            command.Parameters("Hours_Worked_Date").Value = hoursWorked.WorkDate
            command.Parameters.Add(New OleDb.OleDbParameter("Hours_Worked_Amt", CDec(hoursWorked.Quantity).ToString("N", nfi)))
            command.Parameters.Add(New OleDb.OleDbParameter("Employee", employee))
            command.Parameters.Add(New OleDb.OleDbParameter("Billable", hoursWorked.Billable))
            command.Parameters.Add(New OleDb.OleDbParameter("Details", If(String.IsNullOrEmpty(hoursWorked.Details), DBNull.Value, hoursWorked.Details)))

            command.ExecuteNonQuery()
        End Using
    End Sub

    Private Sub InsertRecord(currentDate As Date, issueID As Integer, quantity As Decimal, employee As String, billable As Boolean, details As String, connection As OleDb.OleDbConnection)
        ' Gets a NumberFormatInfo associated with the en-US culture.
        Dim nfi As NumberFormatInfo = New CultureInfo("en-CA", False).NumberFormat

        ' Displays the same value with a blank as the separator.
        nfi.NumberDecimalSeparator = "."

        Dim sqlQuery As String = "INSERT INTO tbl_HoursWorkedLog (Issue_ID, Hours_Worked_Date, Hours_Worked_Amt, Employee, Billable, Details) VALUES (?, ?, ?, ?, ?, ?)"

        Using command As New OleDb.OleDbCommand(sqlQuery, connection)
            command.Parameters.Add(New OleDb.OleDbParameter("Issue_ID", CInt(issueID))) 'Convert.ToInt32(issueID)))
            command.Parameters.Add(New OleDb.OleDbParameter("Hours_Worked_Date", OleDb.OleDbType.Date))
            command.Parameters("Hours_Worked_Date").Value = currentDate
            command.Parameters.Add(New OleDb.OleDbParameter("Hours_Worked_Amt", CDec(quantity).ToString("N", nfi)))
            command.Parameters.Add(New OleDb.OleDbParameter("Employee", employee))
            command.Parameters.Add(New OleDb.OleDbParameter("Billable", billable))
            command.Parameters.Add(New OleDb.OleDbParameter("Details", If(String.IsNullOrEmpty(details), DBNull.Value, details)))

            command.ExecuteNonQuery()
        End Using
    End Sub

#End Region

#Region "JIRA Code"

    Private JIRAdataTable As New DataTable()

    Private Sub Initialize_DGView()
        If GCtrlJIRASearch.DataSource Is Nothing Then
            Telerik.WinControls.UI.RadOverlayManager.Show(Me.GCtrlJIRASearch)

            With Me.GVJIRASearch
                .OptionsView.ColumnAutoWidth = False

                .Columns.Add(New DevExpress.XtraGrid.Columns.GridColumn() With {
                    .FieldName = "Key",
                    .Caption = "Key"
                })
                .Columns.Add(New DevExpress.XtraGrid.Columns.GridColumn() With {
                    .FieldName = "Summary",
                    .Caption = "Summary"
                })
                .Columns.Add(New DevExpress.XtraGrid.Columns.GridColumn() With {
                    .FieldName = "Status",
                    .Caption = "Status"
                })
                .Columns.Add(New DevExpress.XtraGrid.Columns.GridColumn() With {
                    .FieldName = "Assignee",
                    .Caption = "Assignee"
                })
                .Columns.Add(New DevExpress.XtraGrid.Columns.GridColumn() With {
                    .FieldName = "Reporter",
                    .Caption = "Reporter"
                })
                .Columns.Add(New DevExpress.XtraGrid.Columns.GridColumn() With {
                    .FieldName = "Created",
                    .Caption = "Created"
                })
                .Columns.Add(New DevExpress.XtraGrid.Columns.GridColumn() With {
                    .FieldName = "Updated",
                    .Caption = "Updated"
                })
                .Columns.Add(New DevExpress.XtraGrid.Columns.GridColumn() With {
                    .FieldName = "Labels",
                    .Caption = "Labels"
                })
                .Columns.Add(New DevExpress.XtraGrid.Columns.GridColumn() With {
                    .FieldName = "Carriers",
                    .Caption = "Carriers"
                })
                .Columns.Add(New DevExpress.XtraGrid.Columns.GridColumn() With {
                    .FieldName = "FLEXSClients",
                    .Caption = "Clients"
                })
                .Columns.Add(New DevExpress.XtraGrid.Columns.GridColumn() With {
                    .FieldName = "EpicName",
                    .Caption = "Epic Name"
                })
                .Columns.Add(New DevExpress.XtraGrid.Columns.GridColumn() With {
                    .FieldName = "EpicLink",
                    .Caption = "Epic Link"
                })
                .Columns.Add(New DevExpress.XtraGrid.Columns.GridColumn() With {
                    .FieldName = "ReleaseDate",
                    .Caption = "Release Date"
                })
                .Columns.Add(New DevExpress.XtraGrid.Columns.GridColumn() With {
                    .FieldName = "ReleaseName",
                    .Caption = "Release"
                })
                .BestFitColumns()
            End With
        Else
            Telerik.WinControls.UI.RadOverlayManager.Show(Me.GCtrlJIRASearch)
            GCtrlJIRASearch.DataSource = Nothing
        End If

        JIRAdataTable = New DataTable

        With JIRAdataTable.Columns
            .Add("Key", GetType(String))
            .Add("Summary", GetType(String))
            .Add("Status", GetType(String))
            .Add("Assignee", GetType(String))
            .Add("Reporter", GetType(String))
            .Add("Created", GetType(DateTime))
            .Add("Updated", GetType(DateTime))
            .Add("Labels", GetType(String))
            .Add("Carriers", GetType(String))
            .Add("FLEXSClients", GetType(String))
            .Add("EpicName", GetType(String))
            .Add("EpicLink", GetType(String))
            .Add("ReleaseDate", GetType(String))
            .Add("ReleaseName", GetType(String))
        End With

        GCtrlJIRASearch.DataSource = JIRAdataTable
        'GridControl3.MainView. = JIRAdataTable

    End Sub

    Private Sub TxtJQLString_EditValueChanged(sender As Object, e As EventArgs) Handles TxtJQLString.EditValueChanged
        Me.GVJIRASearch.Columns.Clear()

    End Sub

    Private Sub btnSearchFLEXS_Click(sender As Object, e As EventArgs) Handles btnSearchFLEXS.Click
        Initialize_DGView()
        ' Construct the Jira search URL
        Dim url As String = "https://jira.tools.telushealth.com/rest/api/2/search?jql=" + TxtJQLString.Text + "&maxResults=50" '+ SpinMaxRes.Value.ToString

        Try
            ' Create a WebClient to download the JSON response
            Dim client As WebClient = New WebClient()
            client.Headers("Authorization") = "Bearer " + "ODAwNDc5MDE5OTk4Op6GvljcN/HFEyy5z1uJQyoV8F6m"
            Dim json As String = client.DownloadString(url)

            ' Parse the JSON response using Newtonsoft.Json
            Dim obj As JObject = JObject.Parse(json)
            Dim issues As JArray = obj("issues")
            For Each issue In issues
                ' Extract the key and summary fields from each issue
                Dim key As String = issue("key").ToString()
                Dim summary As String = issue("fields")("summary").ToString()
                Dim Status As String = issue("fields")("status")("name").ToString()
                Dim Assignee As String = If(issue("fields")("assignee").Count <> 0, issue("fields")("assignee")("displayName").ToString(), "Unassigned")
                Dim Reporter As String = issue("fields")("reporter")("displayName").ToString()
                Dim Created As DateTime = CDate(issue("fields")("created").ToString())
                Dim Updated As DateTime = CDate(issue("fields")("updated").ToString())
                Dim Labels As String = Strings.Trim(Replace(Replace(Replace(Replace(Replace(issue("fields")("labels").ToString(), """", String.Empty), "[" & vbCrLf, String.Empty), vbCrLf & "]", String.Empty), vbCrLf, String.Empty), "  ", " "))
                Dim Carriers As String = String.Empty
                If issue("fields")("customfield_12704").Count <> 0 Then
                    For i = 0 To issue("fields")("customfield_12704").Count - 1
                        If i = 0 Then
                            Carriers = issue("fields")("customfield_12704").Item(i)("value").ToString
                        Else
                            Carriers += ", " & issue("fields")("customfield_12704").Item(i)("value").ToString
                        End If
                    Next
                End If
                Dim FLEXSClients As String = Strings.Trim(Replace(Replace(Replace(Replace(Replace(issue("fields")("customfield_12705").ToString(), """", String.Empty), "[" & vbCrLf, String.Empty), vbCrLf & "]", String.Empty), vbCrLf, String.Empty), "  ", " "))

                Dim EpicName As String = String.Empty
                Dim EpicLink As String = String.Empty

                Try
                    EpicName = issue("fields")("customfield_10004").ToString()
                    EpicLink = issue("key").ToString()
                Catch ex As Exception
                    'MsgBox(ex.Message & vbNewLine & vbNewLine & "Update failed")
                End Try

                Try
                    If EpicLink = String.Empty Then EpicLink = issue("fields")("customfield_10002").ToString()
                Catch ex As Exception
                    'MsgBox(ex.Message & vbNewLine & vbNewLine & "Update failed")
                End Try

                Dim ReleaseDate As String = String.Empty
                Try
                    ReleaseDate = issue("fields")("fixVersions").Item(0)("releaseDate").ToString()
                Catch
                End Try

                Dim ReleaseName As String = String.Empty
                Try
                    ReleaseName = issue("fields")("fixVersions").Item(0)("name").ToString()
                Catch
                End Try
                JIRAdataTable.Rows.Add(key, summary, Status, Assignee, Reporter, Created, Updated, Labels, Carriers, FLEXSClients, EpicName, EpicLink, ReleaseDate, ReleaseName)

            Next

            Me.GCtrlJIRASearch.RefreshDataSource()
            Me.GVJIRASearch.RefreshData()

            For Each gridColumn As DevExpress.XtraGrid.Columns.GridColumn In GVJIRASearch.Columns
                gridColumn.Visible = True
            Next
            GVJIRASearch.BestFitColumns()



        Catch Ex As Exception
            Select Case Ex.Message
                Case "The remote server returned an error: (400) Bad Request."
                    MsgBox("The request is invalid!", vbExclamation, "Invalid Request")
                Case Else
                    MsgBox(Ex.Message)
            End Select

        End Try
        Telerik.WinControls.UI.RadOverlayManager.Close()
    End Sub

    Private Sub btnJQLSnippets_ListItemClick(sender As Object, e As DevExpress.XtraBars.ListItemClickEventArgs) Handles btnJQLSnippets.ListItemClick
        Dim coucou As DevExpress.XtraBars.BarListItem = e.Item ')(DevExpress.XtraBars.BarListItem = e.Item)
        Me.TxtJQLString.Text = coucou.Strings(e.Index)
        'MsgBox(coucou.Strings(e.Index))
        'Dim cheee As String = coucou.Strings(e.Index)
        'Dim aaa As String = ((e.Item As DevExpress.XtraBars.BarListItem).Strings(e.index))
    End Sub

    Private Sub TxtJQLString_ButtonClick(sender As Object, e As DevExpress.XtraEditors.Controls.ButtonPressedEventArgs) Handles TxtJQLString.ButtonClick
        'Me.TxtJQLString.SelectAll()
        Me.TxtJQLString.Text = String.Empty
        Me.TxtJQLString.Focus()
    End Sub

#End Region

#Region "JIRA Information on a ticket"
    Private Sub MemoEdit1_EditValueChanged(sender As Object, e As EventArgs) Handles MemoEdit1.EditValueChanged


    End Sub

    Private Sub MemoEdit1_Click(sender As Object, e As EventArgs) Handles MemoEdit1.Click
        Dim ticketKey As String = "FLEX-2798"
        ' Fetch the ticket details, including comments and activity history
        Dim detailsRequest As HttpWebRequest = DirectCast(WebRequest.Create("https://jira.tools.telushealth.com/rest/api/2/issue/" & ticketKey & "?expand=changelog"), HttpWebRequest)
        detailsRequest.Headers.Add("Authorization", "Bearer ODAwNDc5MDE5OTk4Op6GvljcN/HFEyy5z1uJQyoV8F6m") ' Replace YOUR_API_TOKEN with your JIRA API token
        detailsRequest.ContentType = "application/json"
        detailsRequest.Method = "GET"

        Dim detailsResponse As WebResponse = detailsRequest.GetResponse()
        Dim detailsReader As StreamReader = New StreamReader(detailsResponse.GetResponseStream())
        Dim detailsResponseString As String = detailsReader.ReadToEnd()

        ' Parse the JSON response to get the comments and activity history
        Dim details As JObject = JObject.Parse(detailsResponseString)
        'Dim summary As String = issue("fields")("summary").ToString()
        Dim comments As JArray = details.SelectToken("fields.comment.comments")
        Dim activityHistory As JArray = details.SelectToken("changelog.histories")

        ' Populate the commentsTextBox
        Dim commentsText As New StringBuilder()
        For Each comment As JObject In comments
            Dim author As String = comment.SelectToken("author.displayName").ToString()
            Dim created As String = comment.SelectToken("created").ToString()
            Dim body As String = comment.SelectToken("body").ToString()

            ' Replace tagged usernames with display names
            Dim regex As New Regex("\[~(\w+)\]")
            Dim matches As MatchCollection = regex.Matches(body)

            For Each match As Match In matches
                Dim taggedUsername As String = match.Groups(1).Value
                Dim taggedDisplayName As String = GetDisplayNameFromUsername(taggedUsername, "ODAwNDc5MDE5OTk4Op6GvljcN/HFEyy5z1uJQyoV8F6m") ' Replace MY_API_TOKEN with your JIRA API token
                body = body.Replace(taggedUsername, taggedDisplayName)
            Next

            commentsText.AppendLine($"Author: {author}")
            commentsText.AppendLine($"Created: {created}")
            commentsText.AppendLine($"Comment: {body}")
            commentsText.AppendLine(New String("-"c, 40))
        Next
        Me.MemoEdit1.Text = commentsText.ToString()

        ' Populate the activityHistoryTextBox
        Dim activityText As New StringBuilder()
        For Each activity As JObject In activityHistory
            Dim user As String = activity.SelectToken("author.displayName").ToString()
            Dim created As String = activity.SelectToken("created").ToString()
            Dim items As JArray = activity.SelectToken("items")

            activityText.AppendLine($"User: {user}")
            activityText.AppendLine($"Created: {created}")

            For Each item As JObject In items
                Dim field As String = item.SelectToken("field").ToString()
                Dim fromString As String = item.SelectToken("fromString").ToString()
                Dim toString As String = item.SelectToken("toString").ToString()

                activityText.AppendLine($"Field: {field}")
                activityText.AppendLine($"From: {fromString}")
                activityText.AppendLine($"To: {toString}")
            Next

            activityText.AppendLine(New String("-"c, 40))
        Next
        Me.MemoEdit2.Text = activityText.ToString()
    End Sub

    Private Function GetDisplayNameFromUsername(ByVal username As String, ByVal apiToken As String) As String
        Dim userRequest As HttpWebRequest = DirectCast(WebRequest.Create("https://jira.tools.telushealth.com/rest/api/2/user?username=" & username), HttpWebRequest)
        userRequest.Headers.Add("Authorization", "Bearer " & apiToken) ' Use the provided API token
        userRequest.ContentType = "application/json"
        userRequest.Method = "GET"

        Dim userResponse As WebResponse = userRequest.GetResponse()
        Dim userReader As StreamReader = New StreamReader(userResponse.GetResponseStream())
        Dim userResponseString As String = userReader.ReadToEnd()

        Dim userDetails As JObject = JObject.Parse(userResponseString)
        Return userDetails.SelectToken("displayName").ToString()
    End Function






#End Region

    'Private Sub GVIssues_CalcRowHeight(sender As Object, e As RowHeightEventArgs) Handles GVIssues.CalcRowHeight
    'End Sub

    Private Sub repoDateEdit_TodayClick(sender As Object, e As EventArgs) Handles repoDateEdit.TodayClick
        'If currentEditor IsNot Nothing Then
        'currentEditor.DateTime = DateTime.Now
        'currentEditor.EditValue = Now

        'currentEditor.RefreshEditValue()

        'currentEditor = TryCast(sender, DateEdit)

        'repoDateEdit.NullDateCalendarValue = Now
        'If IsDBNull(currentEditor.EditValue) Then

        currentEditor.EditValue = DateTime.Now
        'End If

        'End If
    End Sub

    Private Sub GVIssues_InitNewRow(sender As Object, e As InitNewRowEventArgs) Handles GVIssues.InitNewRow
        Dim view As GridView = CType(sender, GridView)
        view.SetRowCellValue(e.RowHandle, view.Columns("Priority"), "(2) Medium")
        view.SetRowCellValue(e.RowHandle, view.Columns("Status"), "Not Started")
        view.SetRowCellValue(e.RowHandle, view.Columns("Date Received"), Now())
    End Sub

    'Private Sub repoDateEdit_BeforePopup(sender As Object, e As EventArgs) Handles repoDateEdit.BeforePopup
    '    'currentEditor = TryCast(sender, DateEdit)
    'End Sub

    Dim currentEditor As DateEdit
    'Private Sub GVIssues_ShownEditor(sender As Object, e As EventArgs) Handles GVIssues.ShownEditor
    'End Sub

    Public Class AddHoursUserControl
        Inherits DevExpress.XtraEditors.XtraUserControl

        Private dtDate As DateEdit
        Private spHours As SpinEdit
        Private chkBillable As CheckEdit
        Private meDetails As MemoEdit

        Public Sub New()
            Dim lc As New DevExpress.XtraLayout.LayoutControl()
            lc.Dock = DockStyle.Fill
            Me.dtDate = New DateEdit() With {.EditValue = Now()}
            Me.dtDate.Properties.CalendarView = Repository.CalendarView.ClassicNew
            Me.dtDate.Properties.CalendarTimeEditing = DevExpress.Utils.DefaultBoolean.True
            Me.dtDate.Properties.SelectionMode = Repository.CalendarSelectionMode.Multiple
            Me.dtDate.SyncSelectionWithEditValue = True
            Me.dtDate.Properties.ShowClear = False
            Me.dtDate.Properties.ShowToday = True
            Me.dtDate.Properties.HighlightTodayCellWhenSelected = False
            Me.spHours = New SpinEdit()
            Me.spHours.Properties.Increment = 0.25
            Me.chkBillable = New CheckEdit() With {.Text = "Billable"}
            Me.meDetails = New MemoEdit
            Me.meDetails.Properties.LinesCount = 3
            lc.AddItem("Date", dtDate).TextVisible = True
            lc.AddItem("Quantity", spHours).TextVisible = True
            lc.AddItem(String.Empty, chkBillable)
            lc.AddItem("Details", meDetails).TextVisible = True
            Me.Controls.Add(lc)
            Me.Height = 200
            Me.Dock = DockStyle.Top
            Me.spHours.Focus()

            AddHandler Me.dtDate.Properties.TodayClick, Sub(sender, e)
                                                            Me.dtDate.DateTime = Now()
                                                            Me.dtDate.EditValue = Now()
                                                        End Sub
        End Sub
        Public ReadOnly Property AddDate() As DateTime
            Get
                Return dtDate.DateTime
            End Get
        End Property
        Public ReadOnly Property DateRange() As DateRangeCollection
            Get
                Return dtDate.SelectedRanges
            End Get
        End Property
        Public ReadOnly Property Quantity() As Double
            Get
                Return spHours.Value
            End Get
        End Property
        Public ReadOnly Property Billable() As Boolean
            Get
                Return Me.chkBillable.Checked
            End Get
        End Property
        Public ReadOnly Property Details() As String
            Get
                Return meDetails.Text
            End Get
        End Property
    End Class

    Public Class AddHoursMultiDaysUserControl
        Inherits DevExpress.XtraEditors.XtraUserControl

        Private dtDate As DateEdit
        Private spHours As SpinEdit
        Private chkBillable As CheckEdit
        Private meDetails As MemoEdit
        Private lc As DevExpress.XtraLayout.LayoutControl
        Private grdView As DevExpress.XtraGrid.GridControl
        Private view As GridView
        Private dataSource As BindingList(Of HoursWorked)
        Private gridViewItem As LayoutControlItem
        Private _workedHours As New BindingList(Of HoursWorked)
        Private gridViewUserControl As GridViewUserControlUC

        Public Property WorkedHours As BindingList(Of HoursWorked)
            Get
                Return _workedHours
            End Get
            Set(value As BindingList(Of HoursWorked))
                _workedHours = value
            End Set
        End Property

        Public Sub New()
            lc = New DevExpress.XtraLayout.LayoutControl()
            lc.Dock = DockStyle.Fill

            dtDate = New DateEdit() With {.EditValue = Now()}
            dtDate.Properties.CalendarView = Repository.CalendarView.ClassicNew
            dtDate.Properties.CalendarTimeEditing = DevExpress.Utils.DefaultBoolean.True
            dtDate.Properties.SelectionMode = Repository.CalendarSelectionMode.Multiple
            dtDate.SyncSelectionWithEditValue = True
            dtDate.Properties.ShowClear = False
            dtDate.Properties.ShowToday = True
            dtDate.Properties.HighlightTodayCellWhenSelected = False

            spHours = New SpinEdit()
            spHours.Properties.Increment = 0.25

            chkBillable = New CheckEdit() With {.Text = "Billable"}

            meDetails = New MemoEdit
            meDetails.Properties.LinesCount = 3

            dataSource = New BindingList(Of HoursWorked)()

            lc.AddItem("Date", dtDate).TextVisible = True
            lc.AddItem("Quantity", spHours).TextVisible = True
            lc.AddItem(String.Empty, chkBillable)
            lc.AddItem("Details", meDetails).TextVisible = True

            Me.Controls.Add(lc)
            Me.AutoSize = True
            Me.AutoSizeMode = AutoSizeMode.GrowAndShrink

            Me.MinimumSize = New Size(300, 200)
            AddHandler dtDate.Closed, Sub()
                                          dataSource.Clear()
                                          For Each selectedRange In dtDate.SelectedRanges
                                              Dim startDate As Date = selectedRange.StartDate
                                              Dim endDate As Date = selectedRange.EndDate
                                              For currentDate As Integer = 0 To ((endDate - startDate).TotalDays - 1)
                                                  If startDate.AddDays(currentDate).DayOfWeek <> DayOfWeek.Sunday And startDate.AddDays(currentDate).DayOfWeek <> DayOfWeek.Saturday Then
                                                      dataSource.Add(New HoursWorked With {.WorkDate = startDate.AddDays(currentDate), .Quantity = Quantity, .Billable = Billable, .Details = Details})
                                                  End If
                                              Next
                                          Next
                                          WorkedHours = dataSource
                                          If dataSource.Count > 1 Then

                                              ShowGridView()
                                          Else
                                              HideGridView()
                                          End If
                                      End Sub
            WorkedHours = dataSource
        End Sub

        Public ReadOnly Property AddDate() As DateTime
            Get
                Return dtDate.DateTime
            End Get
        End Property

        Public ReadOnly Property DateRange() As DateRangeCollection
            Get
                Return dtDate.SelectedRanges
            End Get
        End Property

        Public ReadOnly Property Quantity() As Double
            Get
                Return spHours.Value
            End Get
        End Property

        Public ReadOnly Property Billable() As Boolean
            Get
                Return Me.chkBillable.Checked
            End Get
        End Property

        Public ReadOnly Property Details() As String
            Get
                Return meDetails.Text
            End Get
        End Property
        Private Sub ShowGridView()

            gridViewUserControl = New GridViewUserControlUC()
            gridViewUserControl.UpdateDataSource(dataSource)
            XtraDialog.Show(gridViewUserControl, "Edit multiple entries", MessageBoxButtons.OK)
            WorkedHours = dataSource
        End Sub

        Private Sub HideGridView()
        End Sub

        Private Sub GridViewUserControl_OnConfirm(sender As Object, e As EventArgs)
        End Sub

        Private Sub AddHoursUserControl_Load(sender As Object, e As EventArgs) Handles Me.Load
            Me.AutoSize = True
            Me.AutoSizeMode = AutoSizeMode.GrowAndShrink
        End Sub
    End Class

    Public Class HoursWorked
        Public Property WorkDate As DateTime
        Public Property Quantity As Double
        Public Property Billable As Boolean
        Public Property Details As String
    End Class

    Public Class GridViewUserControlUC
        Inherits DevExpress.XtraEditors.XtraUserControl

        Private gridView As DevExpress.XtraGrid.GridControl
        Private view As GridView
        Private dataSource As BindingList(Of HoursWorked)

        Public Sub New()
            gridView = New DevExpress.XtraGrid.GridControl()
            view = New GridView(gridView)
            gridView.MainView = view
            dataSource = New BindingList(Of HoursWorked)()
            gridView.DataSource = dataSource
            gridView.Dock = DockStyle.Fill

            Me.AutoSizeMode = AutoSizeMode.GrowOnly
            Me.MinimumSize = New Size(900, 400)
            Me.Controls.Add(gridView)
        End Sub

        Public Sub UpdateDataSource(data As BindingList(Of HoursWorked))
            dataSource = data
            gridView.DataSource = dataSource
            gridView.RefreshDataSource()
            view.BestFitColumns()
        End Sub
    End Class


    Public Class AddCommentUserControl
        Inherits DevExpress.XtraEditors.XtraUserControl

        Private meComment As MemoEdit

        Public Sub New()
            Dim lc As New DevExpress.XtraLayout.LayoutControl()
            lc.Dock = DockStyle.Fill
            Me.meComment = New MemoEdit
            Me.meComment.Properties.LinesCount = 3
            Me.meComment.Properties.ScrollBars = ScrollBars.None
            lc.AddItem("Comment", meComment).TextVisible = False
            Me.Controls.Add(lc)
            Me.Height = 100
            Me.Dock = DockStyle.Top
            Me.meComment.Focus()
            lc.GetItemByControl(meComment).Control.Focus()
        End Sub


        Public ReadOnly Property Comment() As String
            Get
                Return meComment.Text
            End Get
        End Property
    End Class

    Public Class AddClientUserControl
        Inherits DevExpress.XtraEditors.XtraUserControl

        Private meClient As TextEdit
        Private meClientID As TextEdit

        Public Sub New()
            Dim lc As New DevExpress.XtraLayout.LayoutControl()
            lc.Dock = DockStyle.Fill
            Me.meClient = New TextEdit
            Me.meClientID = New TextEdit
            lc.AddItem("Client Name", meClient).TextVisible = True
            lc.AddItem("Client ID", meClientID).TextVisible = True
            Me.Controls.Add(lc)
            Me.Height = 85
            Me.Dock = DockStyle.Top
            Me.meClient.Focus()
            lc.GetItemByControl(meClient).Control.Focus()
        End Sub


        Public ReadOnly Property Client() As String
            Get
                Return meClient.Text
            End Get
        End Property
        Public ReadOnly Property ClientID() As String
            Get
                Return meClientID.Text
            End Get
        End Property
    End Class

    Private Sub repoDateEdit_CalendarTimeProperties_ButtonPressed(sender As Object, e As ButtonPressedEventArgs) Handles repoDateEdit.CalendarTimeProperties.ButtonPressed

    End Sub

    'Private Sub GVIssues_EditFormPrepared(sender As Object, e As EditFormPreparedEventArgs) Handles GVIssues.EditFormPrepared
    '    'Me.repoDateEdit.TodayDate = CDate("08/16/2023") 'Now
    'End Sub

    Private Sub BarBtnAddHoursFly_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarBtnAddHoursFly.ItemClick
        Dim frmHoursEdit As New HoursEdit
        frmHoursEdit.Show()
    End Sub

    Private Sub ribbonStatusBar_Click(sender As Object, e As EventArgs) Handles ribbonStatusBar.Click

    End Sub

    Private Sub GVIssues_FocusedRowChanged(sender As Object, e As FocusedRowChangedEventArgs) Handles GVIssues.FocusedRowChanged
        If Me.StatBarUPDSuccess.Visibility = DevExpress.XtraBars.BarItemVisibility.Always Then
            Me.StatBarUPDSuccess.Visibility = DevExpress.XtraBars.BarItemVisibility.Never
        ElseIf Me.StatBarUPDFail.Visibility = DevExpress.XtraBars.BarItemVisibility.Always Then
            Me.StatBarUPDFail.Visibility = DevExpress.XtraBars.BarItemVisibility.Never
        End If
    End Sub

    Private Sub repoDateEdit_QueryPopUp(sender As Object, e As CancelEventArgs) Handles repoDateEdit.QueryPopUp

        currentEditor = TryCast(sender, DateEdit)

        repoDateEdit.NullDateCalendarValue = Now
        If IsDBNull(currentEditor.EditValue) Then
            currentEditor.EditValue = DateTime.Now
        End If
        'repoDateEdit.edit
    End Sub

    'Private Sub repoDateEdit_Popup(sender As Object, e As EventArgs) Handles repoDateEdit.Popup
    '    'If repoDateEdit.ed Then
    'End Sub

    'Private Sub repoDateEdit_ParseEditValue(sender As Object, e As ConvertEditValueEventArgs) Handles repoDateEdit.ParseEditValue

    'End Sub

    Private Sub GVIssues_InvalidRowException(sender As Object, e As InvalidRowExceptionEventArgs) Handles GVIssues.InvalidRowException
        e.ExceptionMode = ExceptionMode.DisplayError 'Ignore
        Select Case ExcValid
            Case "NoFLEXS"
                e.WindowCaption = "FLEXS required!"
                e.ErrorText = "The FLEXS ticket field cannot be left blank when using this status!"
                ExcValid = ""
            Case "CompAndTroubleshoot"
                e.WindowCaption = "Completed request cannot be categorized as Troubleshooting"
                e.ErrorText = "Update the category with the appropriate value and try again"
                ExcValid = ""
        End Select
    End Sub

    Private Sub GVIssues_ValidateRow(sender As Object, e As ValidateRowEventArgs) Handles GVIssues.ValidateRow
        Dim View As GridView = CType(sender, GridView)
        Dim reqStatus As GridColumn = View.Columns("Status")
        Dim reqCat As GridColumn = View.Columns("Category")
        If View.GetRowCellValue(e.RowHandle, reqStatus).ToString = "Completed" And View.GetRowCellValue(e.RowHandle, reqCat).ToString = "Troubleshooting" Then
            e.Valid = False
            ExcValid = "CompAndTroubleshoot"
            'Set errors with specific descriptions for the columns
            'View.SetColumnError(reqStatus, "The value must be greater than Units On Order")
            View.SetColumnError(reqCat, "Completed request cannot have a Troubleshooting category.")
            e.ErrorText = "Completed request cannot have a Troubleshooting category."
        End If
    End Sub

    Private Sub BarButtonItem2_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonItem2.ItemClick
        Dim frmNewJIRA As New CreateFLEX


        frmNewJIRA.Show()
        frmNewJIRA.TxtClientID.EditValue = GVIssues.GetFocusedRowCellValue("Client")
        frmNewJIRA.CboClientName.EditValue = GVIssues.GetFocusedRowCellDisplayText("Client")
    End Sub

    Private Sub BarButtonItem3_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonItem3.ItemClick
        Dim frmDashBrd As New TestDashBoard
        frmDashBrd.Show()
    End Sub

    Private Sub BarBtnNewClient_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarBtnNewClient.ItemClick
        Dim myControl As New AddClientUserControl()
        If XtraDialog.Show(myControl, "Enter Client Names and Flexit ID", MessageBoxButtons.OKCancel) = System.Windows.Forms.DialogResult.OK Then
            QryUpdHoursComments = "INSERT INTO Clients ([Client Name], IDFlexit) VALUES ('" & Replace(myControl.Client, "'", "''") & "', " & myControl.ClientID & ")"
            LoadDataAsync_NavBar("AddClient")
        End If
    End Sub

    Private Sub BarBtnRefresh_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarBtnRefresh.ItemClick
        LoadDataAsync()
    End Sub

    Private Sub BtnAddContactConfirm_Click(sender As Object, e As EventArgs) Handles BtnAddContactConfirm.Click
        QryUpdHoursComments = "INSERT INTO Contacts ([First Name], [Last Name], [E-mail Address], TELUS_ID) VALUES (" & If(String.IsNullOrEmpty(Me.TxtAddContactFName.Text), "NULL", "'" & Replace(Me.TxtAddContactFName.Text, "'", "''") & "'") & ", " & If(String.IsNullOrEmpty(Me.TxtAddContactLName.Text), "NULL", "'" & Replace(Me.TxtAddContactLName.Text, "'", "''") & "'") & ", '" & Me.TxtAddContactEmail.Text & "' , " & If(String.IsNullOrEmpty(Me.TxtAddContactTID.Text), "NULL", "'" & Me.TxtAddContactTID.Text & "'") & ")"
        LoadDataAsync_NavBar("AddContact")
    End Sub

End Class

